-- 1. Create a table to store tender results (Winner & Financials)
CREATE TABLE tender_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_id BIGINT REFERENCES tenders(id) ON DELETE CASCADE,
    winner_name TEXT NOT NULL,
    winning_bid_amount NUMERIC(15, 2), -- The final contract value
    estimated_cost NUMERIC(15, 2),     -- To calculate deviation (e.g., -4.2% below estimate)
    bidder_count INTEGER DEFAULT 0,    -- How many people participated
    contract_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE tender_results ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy (Optional: Allow public read, admin write)
CREATE POLICY "Allow public read of results" ON tender_results FOR SELECT USING (true);

-- 4. Example Queries for the "Intelligence" Engine

-- A. Get Top 5 Bidders in a specific State & Category
-- SELECT winner_name, COUNT(*) as wins 
-- FROM tender_results tr
-- JOIN tenders t ON tr.tender_id = t.id
-- WHERE t.state = 'Maharashtra' AND t.tender_category = 'Civil Works'
-- GROUP BY winner_name 
-- ORDER BY wins DESC 
-- LIMIT 5;

-- B. Calculate Average Competition (Avg Bidders)
-- SELECT AVG(bidder_count) 
-- FROM tender_results tr
-- JOIN tenders t ON tr.tender_id = t.id
-- WHERE t.tender_category = 'Civil Works';
