-- Extended Schema for Detailed Tender Results

-- 1. Table to store individual bidder details for a tender
CREATE TABLE tender_bidders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_id BIGINT REFERENCES tenders(id) ON DELETE CASCADE,
    bidder_name TEXT NOT NULL,
    quoted_amount NUMERIC(15, 2),
    rank INTEGER,               -- e.g., 1 for L1, 2 for L2
    is_technical_qualified BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'Particiapated', -- 'Winner', 'Lost', 'Rejected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE tender_bidders ENABLE ROW LEVEL SECURITY;

-- 3. Policy for public read
CREATE POLICY "Allow public read of bidders" ON tender_bidders FOR SELECT USING (true);

-- 4. Sample Query to get Result Page Data
-- SELECT * FROM tender_bidders WHERE tender_id = 123 ORDER BY quoted_amount ASC;
